### ISSUE TITLE
Choose a License

### ISSUE THREAD

**Issue by paulleosteinberg** [Freeeaky/GTALua#19]
The main advantage of your plugin to http://gtaforums.com/topic/789139-vrelhook-lua-plugin-for-script-hook-v/ IMHO is that its source code is available (which btw is never really mentioned as advantage).

You, though, didn't indicate a license, which makes it very hard to actually use your project. http://choosealicense.com/ might help you to choose a license.

**Comment by Freeeaky** [comment]
Thanks for your interest in the project. I will add a license first thing
after school (which is in 3 hrs).

I guess i'll also add it to the features list. I didn't think it was a big
deal, because modern projects should be open source (imo).

Thanks for the suggestion. May i ask, do you plan on using the source code
to help develop? I would really look forward to that.

**Comment by Freeeaky** [comment]
Added License
https://github.com/Freeeaky/GTALua/commit/dbc69bd4cd8520c198bc17bf425671c4650337aa
